export const FETCH_FILMS = 'FETCH_FILMS';
export const ADD_FILM = 'ADD_FILM';
export const UPDATE_FILM = 'UPDATE_FILM';
export const DELETE_FILM = 'DELETE_FILM';
export const EDIT_FILM = 'EDIT_FILM';

export const FETCH_KIND_FILMS = 'FETCH_KIND_FILMS';
export const ADD_KIND_FILM = 'ADD_KIND_FILM';
export const UPDATE_KIND_FILM = 'UPDATE_FKIND_ILM';
export const DELETE_KIND_FILM = 'DELETE_KIND_FILM';
export const EDIT_KIND_FILM = 'EDIT_KIND_FILM';

export const FETCH_TYPE_FILMS = 'FETCH_TYPE_FILMS';
export const ADD_TYPE_FILM = 'ADD_TYPE_FILM';
export const UPDATE_TYPE_FILM = 'UPDATE_TYPE_ILM';
export const DELETE_TYPE_FILM = 'DELETE_TYPE_FILM';
export const EDIT_TYPE_FILM = 'EDIT_TYPE_FILM';


export const FETCH_EPOSIDE_FILMS = 'FETCH_EPOSIDE_FILMS';
export const ADD_EPOSIDE_FILM = 'ADD_EPOSIDE_FILM';
export const UPDATE_EPOSIDE_FILM = 'UPDATE_EPOSIDE_ILM';
export const DELETE_EPOSIDE_FILM = 'DELETE_EPOSIDE_FILM';
export const EDIT_EPOSIDE_FILM = 'EDIT_EPOSIDE_FILM';